Trying some file copying

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,7 +6,23 @@ BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
 
+
 # Re-exporting APP_SUBDIR as PROJECT_PATH for downstream https://github.com/timanovsky/subdir-heroku-buildpack
 export PROJECT_PATH="$(cat $ENV_DIR/APP_SUBDIR)"
+APP_DIR=$(dirname "${BUILD_DIR}/${PROJECT_PATH}")
 
 echo "=====> Rewriting package references in anticipation of downstream buildpack promoting $PROJECT_PATH to the app root"
+
+# Copy app.json over to maintain review app configurations
+if [[ -f "${BUILD_DIR}/app.json" ]]; then
+  cp "${BUILD_DIR}/app.json" "${APP_DIR}/app.json"
+  echo "Copied ${BUILD_DIR}/app.json to ${APP_DIR}/app.json successfully" | indent
+fi
+
+if [[ -d "${BUILD_DIR}/teamshares_packages" ]]; then
+  cp -f "${BUILD_DIR}/teamshares_packages" "${APP_DIR}/teamshares_packages"
+  echo "Copied ${BUILD_DIR}/teamshares_packages to ${APP_DIR}/teamshares_packages successfully" | indent
+else
+  echo "MISSING teamshares_packages -- are you sure you're in the right repo?" | indent
+  exit 1
+fi
