Half-a-test + valid bash syntax?

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,12 +1,16 @@
 #!/usr/bin/env bash
 
-# if [ ! -d "./teamshares_packages" ]; then
+# if [ ! -d "teamshares_packages" ]; then
 #   echo "Missing teamshares_packages directory -- are you sure you're in the teamshares monorepo?"
 #   exit 1
 # elif [ ! -z "$APP_SUBDIR" ]; then
-#   echo "Missing APP_SUBDIR in env -- must be set as a Heroku config var"
-#   exit 1
-# else
+
+
+# Note: when it DOES fail, it doesn't seem to actually echo these lines to the log...
+if [ ! -z "$APP_SUBDIR" ]; then
+  echo "Missing APP_SUBDIR in env -- must be set as a Heroku config var"
+  exit 1
+else
   echo "Teamshares monorepo buildpack"
   exit 0
-# fi
+fi
