Back to just checking for ENV variable

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,10 +1,12 @@
 #!/usr/bin/env bash
 
-# Note: when it DOES fail, it doesn't seem to actually echo these lines to the log...?
-if [ ! -d "teamshares_packages" ]; then
-  echo "Missing teamshares_packages directory -- are you sure you're in the teamshares monorepo?"
-  exit 1
-elif [ ! -z "$APP_SUBDIR" ]; then
+# # Note: when it DOES fail, it doesn't seem to actually echo these lines to the log...?
+# if [ ! -d "teamshares_packages" ]; then
+#   echo "Missing teamshares_packages directory -- are you sure you're in the teamshares monorepo?"
+#   exit 1
+
+
+if [ ! -z "$APP_SUBDIR" ]; then
   echo "Missing APP_SUBDIR in env -- must be set as a Heroku config var"
   exit 1
 else
